name: CI
on:
  push:

jobs:
  release-please:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  update-nix:
    name: Update Nix Flake
    needs: release-please
    if: needs.release-please.outputs.release_created == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Update hashes
        id: update-hashes
        run: |
          # Get src hash
          sed -i 's/sha256 = ".*";/sha256 = "";/' flake.nix
          SRC_HASH=$(nix build 2>&1 | grep -oP 'got:\s+\Ksha256-[a-zA-Z0-9+/]*' | head -1)
          sed -i "s/sha256 = \".*\";/sha256 = \"$SRC_HASH\";/" flake.nix

          # Get vendor hash
          sed -i 's/vendorHash = ".*";/vendorHash = "sha256-AAAA";/' flake.nix
          VENDOR_HASH=$(nix build 2>&1 | grep -oP 'got:\s+\Ksha256-[a-zA-Z0-9+/]*' | head -1)
          sed -i "s/vendorHash = \".*\";/vendorHash = \"$VENDOR_HASH\";/" flake.nix
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(nix): update flake.nix hashes"

  goreleaser:
    name: Publish
    needs: [release-please, update-nix]
    if: needs.release-please.outputs.release_created == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
